[package]
name = "tlg_rs"
version = "0.1.0"
authors = ["forlos <forlos@disroot.org>"]
edition = "2018"

[dependencies]
scroll = { version = "0.10.1", features = ["derive"] }
image = "0.22.4"
lazy_static = "1.4.0"
byteorder = "1.3.2"
structopt = "0.3.8"
